### ISSUE TITLE
Can the extension support VScode's difftool view?

### ISSUE THREAD

**Issue by genesy** [asvetliakov/vscode-neovim#191] opened 2020-02-19 07:22 UTC
When viewing git diff the extension doesn't work on the changes side.

![image](https://user-images.githubusercontent.com/1282480/74811023-95ca8c80-532b-11ea-9e2e-75f5369f2df8.png)

**Comment by asvetliakov** [comment] 2020-02-19 10:18
Yes, it can.
Duplicate of #53

**Closed by asvetliakov** 2020-02-19 10:18 UTC
