### ISSUE TITLE
"Visual Selection starts visual mode" not working + how to unbind keys ? 

### ISSUE THREAD

**Issue by StitiFatah** [asvetliakov/vscode-neovim#450] opened 2020-12-13 12:13 UTC
Os : Archlinux
vscode : the open source release  "Code"
neovim : 0.5.0 

I just installed the extension because VscodeVim was too slow, I like to be able to copy with ctrl+c when selecting text with the mouse, with vscode vim i used to do :    
```
"vim.handleKeys": {
    "<C-c>": false,
} 
```
in my settings.json but can't find a way to do it with vscode-neovim. 
I thought enabling visual mode on select with : 
`"vscode-neovim.mouseSelectionStartVisualMode": true`

may do the job to then copy using the vim way but unfortunately the option doesn't seem to work, selecting with mouse doesn't change the mode. 

Thanks for reading.

**Comment by theol0403** [comment] 2020-12-14 05:01
The mouse mode seems to have some problems, not sure if there is a fix at this point. 
To unbind, you can go to the keybindings page of vscode, find the keybinding you want to remove, right-click and delete.

**Comment by trusktr** [comment] 2020-12-22 20:52
I was about to report the same, but found this issue. I just tried this extension for the first time. It is really great, bringing us a more accurate (actual) vim experience in VS Code! :tada: 

What I noticed is that clicking once does move the cursor, but clicking and dragging is where it doesn't work.

**Comment by asvetliakov** [comment] 2021-01-03 21:02
duplicate of #395

**Closed by asvetliakov** 2021-01-03 21:02 UTC
