### ISSUE TITLE
Yanked text is malformed

### ISSUE THREAD

**Issue by dobrovolsky** [asvetliakov/vscode-neovim#416] opened 2020-10-26 20:08 UTC
For some reason, the Cyrillic text is malformed if yanked from vscode.
- For example yanked line (`yy`) with `тест test` stored in the buffer as `—Ç–µ—Å—Ç test`.  
- If use `pp` paste works as expected (works only in vscode).
- But for other programs and even vscode, if paste in insert mode with `cmd + c` it's malformed.
- In nvim everything works as expected and puts `тест test` in buffer.

**settings.json**
```json
{
    "vscode-neovim.neovimInitVimPaths.darwin": "~/.config/nvim/init.vim",
    "vscode-neovim.neovimExecutablePaths.darwin": "/usr/local/bin/nvim"
}
```

**init.vim**
```
set clipboard+=unnamed
```

**nvim's version**
```bash
❯ v --version 
NVIM v0.5.0-a22fe09
Build type: Release
LuaJIT 2.0.5
```

**Comment by asvetliakov** [comment] 2021-01-03 21:21
duplicate of #266

**Closed by asvetliakov** 2021-01-03 21:21 UTC
Labels: bug
