### ISSUE TITLE
History of search patterns doesn't work

### ISSUE THREAD

**Issue by dim-an** [asvetliakov/vscode-neovim#552] opened 2021-02-12 09:15 UTC
When searching in `vim`/`nvim` you can use `<Up>`/`Down` to select patterns from history. Looks like this functionality doesn't work in `vscode-neovim`.

**Comment by Shatur95** [comment] 2021-02-12 09:33
Duplicate of #514.

**Closed by Shatur95** 2021-02-12 09:33 UTC

**Comment by dim-an** [comment] 2021-02-12 10:09
Nice! Thank you!
