### ISSUE TITLE
feature requested -- supporting cmdline window feature

### ISSUE THREAD

**Issue by rilakkumars** [asvetliakov/vscode-neovim#451] opened 2020-12-15 00:36 UTC
Hi,
vscode-neovim is an amazing plugin that I really love it. Here I want to propose a new feature: supporting cmdline window.

In vim/neovim normal mode you can type "q:" "q/" "q?" to open a dedicated window where you can edit you ex command or search pattern in "insert mode" and also move around chars in normal mode. Once you are done with your ex command or search pattern, you can type enter to make vim/neovim execute them.  The details are recorded in vim doc :h cmdline-window. It would be perfect that vscode-neovim can support this feature like open a new editor to allow us to edit the command/pattern, and send it to neovim process.

**Comment by asvetliakov** [comment] 2021-01-03 21:01
duplicate of #294

**Closed by asvetliakov** 2021-01-03 21:01 UTC
