### ISSUE TITLE
Do not focus on searched word

### ISSUE THREAD

**Issue by cirelli94** [asvetliakov/vscode-neovim#486] opened 2020-12-30 16:30 UTC
I'm editing this document attached, when I search with `/` the word `licenses`.
There are two occurrences but only the first get the focus.
When I press `n` to go to the next one, it change the counter at the bottom but it doesn't move the cursor and focus on the second word.
First search:
![image](https://user-images.githubusercontent.com/1636493/103367045-64325e00-4ac4-11eb-98bf-02ecde831605.png)
After I press `n`:
![image](https://user-images.githubusercontent.com/1636493/103367054-6b596c00-4ac4-11eb-8344-e6b6b418b886.png)

File where it happens attached.

[sample.json.txt](https://github.com/asvetliakov/vscode-neovim/files/5754904/sample.json.txt)

```
$ nvim --version 
NVIM v0.5.0-828-g0a95549d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-abaca5c2-51e7-4cf1-bc06-8cf3e644ab24

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
```
$ code --version 
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```

asvetliakov.vscode-neovim
v0.0.72

**Comment by asvetliakov** [comment] 2020-12-30 16:35
Try to update neovim nightly

**Comment by theol0403** [comment] 2020-12-31 03:25
Duplicate of #488

**Closed by theol0403** 2020-12-31 03:25 UTC
