### ISSUE TITLE
Support for Visual studio online

### ISSUE THREAD

**Issue by hholst80** [asvetliakov/vscode-neovim#246] opened 2020-04-25 13:32 UTC
I just tried to install the neovim plugin on vsonline and I got the following error message:

> Cannot install 'Neo Vim' because this extension has defined that it cannot run on the remote server.

**Comment by asvetliakov** [comment] 2020-09-08 01:38
Related #262

**Comment by hholst80** [comment] 2020-09-09 16:31
I think they are identical issues. You could close this one as a duplicate in favor of #262 as it seems it has more comments and interactions to it than this issue.

**Comment by theol0403** [comment] 2021-06-04 20:12
Duplicate of #262 👍

**Closed by theol0403** 2021-06-04 20:12 UTC
Labels: enhancement
