### ISSUE TITLE
Focus jumps to latest position when switching tabs

### ISSUE THREAD

**Issue by amitlevy21** [asvetliakov/vscode-neovim#427] opened 2020-11-06 09:10 UTC
Please see at: ( sorry couldn't convert it to gif)
https://webmshare.com/play/PxBdq

As you can see, I have the first file opened, I move the cursor to the line where it says "test", scroll back to the top of that file without moving the cursor. Then I change to a different file in a different tab and when I change back to the previous file, the file focus is change (there is a "jump") to the cursor.

This really bugs me and distracts me when I'm trying to write code. Is this intended? Is there a way to disable this behavior?

Thanks.

**Comment by amitlevy21** [comment] 2020-11-06 12:38
Forgot to mention that I tried reproducing after disabling all extensions ( did not reproduce). Afterwards I enabled all extensions besides neovim and it would not reproduce. It only happens when this extension is enabled.

**Comment by kwonoj** [comment] 2020-11-09 23:29
Trying to isolated, this seems to happen anytime visible document editor changes with trying to setting new buffer: https://github.com/asvetliakov/vscode-neovim/blob/dbd943f21265a0da3d5efab87d3ecf3011cdc369/src/buffer_manager.ts#L400 . I'm not sure why setting buffer changes viewport of given editor though, hard to think of way to fix.

**Comment by kwonoj** [comment] 2020-11-09 23:30
I was thinking this is dupe of https://github.com/asvetliakov/vscode-neovim/issues/404 but doesn't look like so, both became hard blocker on daily workflow.

**Comment by asvetliakov** [comment] 2020-11-09 23:42
>. I'm not sure why setting buffer changes viewport of given editor though, hard to think of way to fix.

Because setting buffer triggers cursor update from neovim which triggers revealing cursor in vscode. Disabling/Opting-out this behavior will break much things.

I'm not sure it's fixable. Perhaps we can keep editor visible ranges in an internal state, then restore them, along with forcing in vim's cursor-follows-scroll behavior (i've tried to make it once, was buggy due to lake of vscode api)

**Comment by kwonoj** [comment] 2020-11-09 23:48
I have very few knowledge around current vscode-neovim's arch so please forgive dumb q: is there specific reason we have to set buffer everytime document changes? is it possible to maintain neovim buffer internally and do not re-set buffer when active / visible document changes? most of cases, editable document won't change its contents when active/visible event emits.

**Comment by asvetliakov** [comment] 2020-11-09 23:53
>is there specific reason we have to set buffer everytime document changes?

yup:
editor column (vscode column with a set of tabs) -> neovim window
editor document -> neovim buffer

Each time we change an editor tab we must update current buffer in some window (column), otherwise neovim wouldn't have a knowledge what document we're editing

**Comment by David-Else** [comment] 2020-11-24 13:52
Really hope this gets fixed, it is really annoying and happens often. Vim shortcuts are all about not being annoying :)

**Comment by astier** [comment] 2020-11-25 12:32
Wouldn't be a solution to disable off-screen-cursor just like in neovim?

**Comment by awilkins** [comment] 2020-12-12 21:06
I think the event sequence is this

Setup :
- Open multiple buffers
- Place cursor
- Use scroll wheel to place cursor offscreen
- Click in other buffer

Bug :
- Click back into first buffer
  a) Buffer scrolls to display previous cursor position
  b) Click event sets cursor to new position
     - This is offscreen, so ... 
  c) Buffer scrolls to display cursor again
     - This only requires the cursor to be at the edge, so this causes the window to jump

If a) didn't happen, it would be OK.

**Comment by asvetliakov** [comment] 2020-12-28 23:20
Fixed with `0.0.70`

**Closed by asvetliakov** 2020-12-28 23:20 UTC

**Comment by amitlevy21** [comment] 2020-12-30 08:14
Thank you!
