### ISSUE TITLE
Cursor moves incorrectly on Chinese characters

### ISSUE THREAD

**Issue by DrakeXiang** [asvetliakov/vscode-neovim#91] opened 2019-12-12 03:15 UTC
Given a string like this: `'当节点连接异常时，您可以尝试节点切换'`.
Move cursor horizontally on it using `hl` or arrow keys, cursor jumps every three characters

**Comment by asvetliakov** [comment] 2019-12-12 03:15
duplicate of #69

**Closed by asvetliakov** 2019-12-12 03:15 UTC
