### ISSUE TITLE
Escape repeat insert code

### ISSUE THREAD

**Issue by letzabelin** [asvetliakov/vscode-neovim#678] opened 2021-06-23 11:19 UTC
Hi!

When I type in insert mode open or close bracket `() [] {}`, then move to command mode - inserted code repeats. Works like dot command

https://user-images.githubusercontent.com/40225759/123088035-ec6b3d80-d42d-11eb-9464-d13561c7941d.mp4

**Comment by theol0403** [comment] 2021-06-24 06:25
Duplicate of #540. We don't know the cause and why it only happens for some people sometimes. I have never been able to reproduce.

**Closed by theol0403** 2021-06-24 06:25 UTC
