### ISSUE TITLE
The undo command doesn't remove the vscode tab's flag

### ISSUE THREAD

**Issue by RidanDev** [asvetliakov/vscode-neovim#447] opened 2020-12-09 22:22 UTC
**To reproduce** 
Just enter the insert mode and start typing something.
A flag will appear in the VSCode's tab indicating the file has been changed.
Enter normal mode and type _u_ to undo.
The flag will stick there in the tab.
(The same problem happens with _ctrl-r_)

**Expected behaviour**
If you perform this same operation but instead of pressing _u_ you press _ctrl+z_ the file will return to a clean state, this should be the same for _u_

There was the same issue with the Vim extension of VSCode. 
That was fixed by adding the following:
```
"vim.normalModeKeyBindings": [
        {
            "before" : ["u"],
            "commands" : [
                "undo"
            ]
        },
        {
            "before" : ["<C-r>"],
            "commands" : [
                "redo"
            ]
        }
    ]

```
**Environment:**
Extension (Neo Vim) version: 0.0.63
VSCode version: 1.51.1
OS: MacOS Big Sur 11.0.1

**Comment by asvetliakov** [comment] 2021-01-03 20:56
duplicate of #247

**Closed by asvetliakov** 2021-01-03 20:56 UTC
