### ISSUE TITLE
Suggestion: add re-sync command

### ISSUE THREAD

**Issue by DanielFabian** [asvetliakov/vscode-neovim#645] opened 2021-05-26 10:00 UTC
How hard / easy would it be add a re-sync command? I've observed de-sync happen quite often in larger developments where a language server takes a while and my only option is to reload the window.

How hard would it be to add either a re-sync command or do a periodic check of sorts and re-sync? Since the de-sync I usually observe is of the kind, where characters are lost, asking if the number of chars in the doc equals the number of chars in buffer, should be a fairly good proxy for detecting a de-sync.

**Comment by guyguy2001** [comment] 2021-06-18 20:42
> I've observed de-sync happen quite often in larger developments where a language server takes a while
Could you elaborate? I've had quite a lot of de-syncs myself, and I've been wondering what causes them.

**Comment by theol0403** [comment] 2021-06-20 01:07
@guyguy2001 I have not had a desync in months, so it's probably something to do with your config or plugins.

Duplicate of #250, #183

**Closed by theol0403** 2021-06-20 01:07 UTC
