### ISSUE TITLE
Ctrl-U / Ctrl-D scrolling in visual selection doesn't work at all

### ISSUE THREAD

**Issue by dahmc** [asvetliakov/vscode-neovim#443] opened 2020-12-04 08:55 UTC
I see this comment on the readme:
> Scrolling is done by VSCode side. <C-d>/<C-u>/etc... are slighly different

The problem is, when I select a few lines after Ctrl-V, and then do Ctrl-D, it moves down, but the selection is not expanded at all, which makes it useless.

Also, when I'm on the last page, Ctrl-D doesn't jump at all anymore, even when my cursor is at the top of the last page.

Can this somehow be handled properly by neovim? It's kind of a big issue not having those jumps working with selection

**Comment by aisopous** [comment] 2020-12-18 01:25
Ctrl-D/Ctrl-U don't update cursor position for me

**Comment by asvetliakov** [comment] 2021-01-03 20:31
Duplicate of #293

**Closed by asvetliakov** 2021-01-03 20:31 UTC
