### ISSUE TITLE
`x` doesn’t work as expected

### ISSUE THREAD

**Issue by firexcy** [asvetliakov/vscode-neovim#572] opened 2021-03-11 14:04 UTC
In command line Vim, `x` deletes all selected characters in visual mode, while in vscode-neovim, it only deletes a single character under cursor.

**Comment by samvv** [comment] 2021-03-16 17:37
I can't reproduce this with the latest release of the extension. `x` deletes the entire visual block for me. Have you tried with an empty `init.vim` without any plugins? You can point to a custom one using `vscode-neovim.neovimInitPath`.

**Comment by guyguy2001** [comment] 2021-03-18 23:30
@firexcy, did you select the characters you wanted to delete with the mouse, or with the keyboard?

Currently the extension does not automatically make your mouse selection into a neovim visual mode selection, so when you press x neovim isn't aware of the selection; You can read #395 and [here](https://github.com/asvetliakov/vscode-neovim#important) for more info about this.

**Comment by firexcy** [comment] 2021-03-19 01:40
> @firexcy, did you select the characters you wanted to delete with the mouse, or with the keyboard?
> 
> Currently the extension does not automatically make your mouse selection into a neovim visual mode selection, so when you press x neovim isn't aware of the selection; You can read #395 and [here](https://github.com/asvetliakov/vscode-neovim#important) for more info about this.

Ah yes I think this is where my issue comes from. I hope there can be a fix — Vim is keyboard-first by definition but mouse selection can be handy in many circumstances.

**Comment by theol0403** [comment] 2021-06-05 19:19
There are already some open issues for syncing vscode selection with neovim, so I'll close this issue in favour of those.

**Closed by theol0403** 2021-06-05 19:19 UTC
