### ISSUE TITLE
Buffer desync on undo / redo.

### ISSUE THREAD

**Issue by feluxe** [asvetliakov/vscode-neovim#269] opened 2020-05-22 11:54 UTC
I have a critical issue with `vscode-neovim`.

Sometimes when I hit `u` to undo changes the buffer gets totally out of sync with what I have in VSCode. When this state is reached, every keystroke becomes *dangerous*. The more I enter the more I destroy my work.  If I hit `ctrl+r` in order to *redo* changes the buffer gets further destroyed. I couldn't find a way to recover my work from this state. The best I could do was closing the buffer, reopen it (this gets the buffer back in sync) and repair the mess. I have lost some work that way multiple times.

This happens on both of my workstations and yet I can't tell why it happens. I haven't noticed a pattern or anything. It hits me out of the blue. I get this issue ~ once a day.

This is my `init.vscode.vim`:

```
" Copy & Paste / Clipboard setting
" --------------------------------

" set clipboard^=unnamed,unnamedplus
set clipboard=unnamedplus
```

**Comment by kcajf** [comment] 2020-06-01 17:26
I have a similar issue, also might be caused by having `set clipboard=unnamedplus`, though hard to be sure since I can't reproduce it consistently.

**Comment by cevn** [comment] 2020-06-19 17:18
I just encountered this. It started after I was doing a macro, actually, this was my first experience with the plugin basically. Probably something in my init.vim

**Comment by asvetliakov** [comment] 2020-06-19 17:51
Need repro steps.

Also may be related to #116

**Comment by cevn** [comment] 2020-06-19 18:03
I will try to repro tonight.

**Comment by alexozer** [comment] 2020-06-23 20:26
Interestingly enough I've encountered something very similar with the normal vscode vim plugin. No idea what the actual cause is, but undoing/redoing becomes just as dangerous as OP suggested.

**Comment by bbronosky-cw** [comment] 2021-05-21 01:01
Any update on this? I can't get redo to work at all.

1. Should I be doing something other than `CTRL-R`?

I get the desync [almost] every time I try.

2. Is there anything that can be done to resync after this happens?

**Comment by DanielFabian** [comment] 2021-05-26 10:17
@feluxe I think I have seen a very similar issue. In my case, using vscode's undo command instead of neovim's helps. Does it work for your case?

**Comment by theol0403** [comment] 2021-06-20 00:50
I have not had a desync in a long time, but when I do, I enter insert mode, and use vscode's undo with `ctrl+z`. 

@bbronosky-cw It must be a problem with your config, `CTRL-R` should work properly. 

Has a desync happen for anyone since 0.60 released in Sept 2020? It seems to have resolved most of them.

I'm going to close this issue, because it is for an older version of the plugin, is probably mostly from config issue. Comment here or open a new issue if this problem continues.

**Closed by theol0403** 2021-06-20 00:50 UTC
Labels: bug, need more info

**Comment by robclancy** [comment] 2022-06-05 07:35
This issue always happens to me and it's infuriating.

**Comment by lithp** [comment] 2022-09-20 04:14
This issue happens with me in v0.0.89, my config is minimal and seems unlikely to be causing the problem (a few `nnoremap` for navigating between splits, `set ignorecase` and `set smartcase`)

**Comment by tengyifei** [comment] 2023-05-12 21:46
I'm still having desync triggered by undo as of `v0.0.97`
