### ISSUE TITLE
Repeat command (.) does not do insertions

### ISSUE THREAD

**Issue by DanielPower** [asvetliakov/vscode-neovim#206] opened 2020-02-28 14:01 UTC
Neo Vim version: 0.5.0
Operating System: OSX 10.15.3
VS Code version: 1.42.1

Example:
Open a blank file
`<a>foo<esc><.><.><.>`

The expected output would be `foofoofoofoo`, but vscode-neovim does not actually input text when using the repeat command. It seems it does repeat normal mode commands, because if you do the same thing but entering insert mode with `<i>`, it will move the cursor back every time you press `<.>`

**Comment by asvetliakov** [comment] 2020-02-28 14:36
duplicate of #76

**Closed by asvetliakov** 2020-02-28 14:36 UTC
