### ISSUE TITLE
Feature request: Ctrl-o in insert mode

### ISSUE THREAD

**Issue by knorrest** [asvetliakov/vscode-neovim#335] opened 2020-09-03 08:30 UTC
Executing normal mode commands while remaining in insert mode using Ctrl-o is something I use a lot in vim. It would be great to have here as well.

**Comment by Shatur95** [comment] 2020-09-03 08:32
Insert mode shortcuts is not supported. But you can just map this commands yourself.

**Comment by theol0403** [comment] 2020-09-03 08:33
I feel like this is a duplicate, but I can't quickly find it.
Anyways, the solution is to add this to your keymaps (until it gets added to the plugin):
```
  {
    "key": "ctrl+o",
    "command": "vscode-neovim.send",
    "args": "<c-o>",
    "when": "editorTextFocus && neovim.mode == insert"
  },
```

**Comment by Shatur95** [comment] 2020-09-03 08:35
Yes, duplicate of #181.

**Comment by knorrest** [comment] 2020-09-03 08:38
Sorry for duplicating, I should have found that. I'll try using the keymap - thx!

**Closed** 2020-09-03 08:38 UTC
