### ISSUE TITLE
More features for multi cursors

### ISSUE THREAD

**Issue by gkssjovi** [asvetliakov/vscode-neovim#620] opened 2021-04-25 17:21 UTC
Hello,

It is possible to implement the multi cursors like the extension VSCodeVim.
When I'm in normal mode I should be able to move all the cursors.
For the moment it implements the multiple cursors only in insert mode.

Kind Regards,
Ovidiu

**Comment by theol0403** [comment] 2021-06-05 19:56
Duplicate of #97

**Closed by theol0403** 2021-06-05 19:56 UTC
