### ISSUE TITLE
Append at end of line and visual selection highlights broken for lines longer than 999 characters

### ISSUE THREAD

**Issue by suncho** [asvetliakov/vscode-neovim#660] opened 2021-06-07 00:35 UTC
If I append at the end of the line (shift-A) on a line with a length between 1000 and 1498 characters, it inserts at column 1000.

If I append to a line with a length greater than 1498 characters, it inserts at column 501.

999: 1000
1498: 501

The highlights for visual selection similarly break down for long lines.  Only the first 999 or 500 characters are highlighted and the cursor is in the wrong spot.

The problem remains if I disable all other extensions.

I'm on Windows 10.

```
NVIM v0.5.0-dev+1381-gb3e3ab056
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-886

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

**Comment by theol0403** [comment] 2021-06-07 02:37
I'm going to mark this as a duplicate of #573, generally this plugin has issues with long lines. If you want to comment on that issue feel free 👍 

Duplicate of #573

**Closed by theol0403** 2021-06-07 02:37 UTC
