### ISSUE TITLE
Keyboard shortcut or command to enable/disable neovim plugin?

### ISSUE THREAD

**Issue by andyw8** [asvetliakov/vscode-neovim#688] opened 2021-07-01 21:13 UTC
Hi, I'm looking for a way to temporarily disable vscode-neovim while pairing with someone who's not a vim user. Is this possible? I couldn't find any existing command.

(it seems it's [possible with VSCodeVim](https://stackoverflow.com/questions/61818446/how-do-i-add-a-keyboard-shortcut-to-activate-disable-a-vscode-extension)).

**Comment by theol0403** [comment] 2021-07-03 20:03
Duplicate of #101

**Closed by theol0403** 2021-07-03 20:03 UTC
