### ISSUE TITLE
request?: do :commands on the vscode statusbar

### ISSUE THREAD

**Issue by lucastrvsn** [asvetliakov/vscode-neovim#328] opened 2020-08-27 22:28 UTC
Hello! First of all thank you for this awesome plugin. Works with my massive init.vim without any issue.

When I'm using neovim from terminal, all the commands displays on the bottom of my terminal. Using this plugin popup one menu on top and then I enter my commands/search etc. I think will be much more "natural" to all neovim/vim users to use with commands ocurring on the bottom of the screen as well. Maybe have some option to disable/enable this behaviour.

Thank you so much for this and if you find it relevant I can work on this!

**Comment by Shatur95** [comment] 2020-08-28 07:41
Looks like duplicate of #297.

**Comment by asvetliakov** [comment] 2020-08-28 14:30
Yep, dupe

**Closed by asvetliakov** 2020-08-28 14:30 UTC
