### ISSUE TITLE
Question: How do I use ctrl+j/k for "quickfix" suggestions?

### ISSUE THREAD

**Issue by Industrial** [asvetliakov/vscode-neovim#640] opened 2021-05-16 11:54 UTC
Hi!

I have this keybinding

```
{ "key": "ctrl+j", "command": "selectNextSuggestion", "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible" }
```

This doesn't work for the quickfix suggestion popup opened with `ctrl + .`. (`problems.actions.showQuickFixes`)

**Comment by theol0403** [comment] 2021-05-17 18:27
Duplicate of #469.

**Closed by theol0403** 2021-05-17 18:27 UTC
