### ISSUE TITLE
VS Code mouse selection is not transfered to Neovim

### ISSUE THREAD

**Issue by zezic** [asvetliakov/vscode-neovim#395] opened 2020-10-02 23:11 UTC
When selecting something with mouse on the VS Code side in normal mode only single character which was under cursor is affected by Vim command instead of whole selection.

**Comment by EvsWorld** [comment] 2020-10-09 10:49
I have same

**Comment by Shatur95** [comment] 2020-10-09 10:55
Please, read the readme [about this](https://github.com/asvetliakov/vscode-neovim#important).

**Comment by zezic** [comment] 2020-10-09 11:40
The readme saying about Neovim -> VS Code, but not about VS Code -> Neovim. It would be better to mention such case as well.

**Comment by Shatur95** [comment] 2020-10-09 11:54
Yes, unfortunately mouse selection produces Neovim selection.

**Comment by lukeburns** [comment] 2021-01-04 20:52
@Shatur95 the problem is that mouse selection does _not_ produce Neovim selection. 

For instance, while in visual mode, if you select using Shift + ← or the mouse, then x to cut, it does not cut your selection — it only cuts a single character. 

I don't mind if selection doesn't propagate in the Neovim -> VS Code direction, but failure to propagate from VS Code to Neovim makes the extension a lot less usable.

**Comment by asvetliakov** [comment] 2021-01-04 20:56
There is the option `Mouse selection start visual mode` but it's broken for a while. 

>but failure to propagate from VS Code to Neovim makes the extension a lot less usable.

Only relatively small subset of vim users are using mouse to select something, although i agree it's pain for those who get used to it

**Comment by Shatur95** [comment] 2021-01-04 21:53
@lukeburns, yep, typo :)

**Comment by lukeburns** [comment] 2021-01-05 02:30
Ah gotcha!

**Comment by autonomic** [comment] 2021-02-24 20:08
> There is the option `Mouse selection start visual mode` but it's broken for a while.
> 
> > but failure to propagate from VS Code to Neovim makes the extension a lot less usable.
> 
> Only relatively small subset of vim users are using mouse to select something, although i agree it's pain for those who get used to it

Ya it's probably not at the top of the list but I do know that I use it from some habits I've developed inside tmux. I don't use it all the time but when I want it it's nice when it's available. Would this be a hard fix?

**Comment by meotimdihia** [comment] 2021-04-20 07:37
For selection, the mouse is faster than hotkey VIM in a lot of cases.

**Comment by account-sxf** [comment] 2021-07-02 01:06
For those maybe annoyed by this, I have tried to internalize the idea that insert mode is the mouses domain only, since this is where vscode takes over the most. You can use the mouse to select and use OS bindings (e.g. Ctrl+C, Ctrl+V) and things like clipboard manager (I'm using qclip at the moment) when using the mouse and remaining in insert mode. It might be a bit clumsy using the keyboard for selection to use neovim, but if you time yourself I think you'll find keyboard and mouse are pretty equivalent for selecting text but the speed-ceiling is maybe higher for proficient keyboard users - so it makes sense that that's the priority.

In saying that, I would loooove to see this bug fixed in an upcoming release. I love this extension and use it every day, and sometimes I'd prefer if all the normal neovim functionality was there like directly in neovim so I don't have to go in to a different mental-space as above.

**Comment by scallaway** [comment] 2021-08-03 14:39
This is a big sticking point for me and I too would love to get this fixed.

I don't have much knowledge of the implementation of this extension, but previously I was using `VSCodeVim` and that has mouse selection for visual mode.

If someone wants to elaborate on the issue a bit more, I'm happy to take a look at it. Absolutely loving the fact that I can use Nevoim in VSCode, and get the best of both worlds (especially since the v0.50 release!).

**Comment by asvetliakov** [comment] 2021-08-03 16:17
@scallaway It's not possible to implement this because neovim just don't have a way to fetch selection ranges except ones within the neovim viewport. The default viewport is 200 lines, so if you're trying to do something like `vi{` inside 500 line code block - only 200 lines will be selected which is just wrong.

**Comment by cspotcode** [comment] 2021-08-11 17:16
Looks like the mouse selection option is passed into `MainController`:
https://github.com/asvetliakov/vscode-neovim/blob/a4735e901cb154a91bd36643970abf4d953622a3/src/extension.ts#L21
https://github.com/asvetliakov/vscode-neovim/blob/a4735e901cb154a91bd36643970abf4d953622a3/src/extension.ts#L37-L46

Declared on `MainController`'s options here:
https://github.com/asvetliakov/vscode-neovim/blob/a4735e901cb154a91bd36643970abf4d953622a3/src/main_controller.ts#L34-L50

But ignored here:
https://github.com/asvetliakov/vscode-neovim/blob/a4735e901cb154a91bd36643970abf4d953622a3/src/main_controller.ts#L201-L210

Additionally, it looks like changing the option will not take effect until the extension is restarted.

Hopefully this is a good starting point for anyone who wants to attempt a fix.

**Comment by yogeshdhamija** [comment] 2021-10-03 13:39
Another use-case is if you want to map a vim key to use vscode's capabilities to expand/shrink selections. I'd like to do this, but am unable to, because the vscode's expanded/shrinked selection doesn't get converted to a vim one. 

Is there any movement on merging the PR with the fix?

**Comment by theol0403** [comment] 2022-01-21 02:20
Fixed by #723

**Closed by theol0403** 2022-01-21 02:20 UTC
Labels: bug
