### ISSUE TITLE
Ctrl+f / Ctrl+b / Ctrl+d / Ctrl+u, these keys doesn't update visual selection.

### ISSUE THREAD

**Issue by unisons** [asvetliakov/vscode-neovim#541] opened 2021-01-29 05:32 UTC
When I start visual selection via shift+v then select more lines with Ctrl+f/b/d/u, the visual selection is not updated.
Is there any way to resolve this issue?

**Comment by theol0403** [comment] 2021-06-05 19:24
Duplicate of #580

**Closed by theol0403** 2021-06-05 19:24 UTC
