### ISSUE TITLE
"dot" command doesn't remember last edit

### ISSUE THREAD

**Issue by kjjuno** [asvetliakov/vscode-neovim#164] opened 2020-01-31 16:31 UTC
One killer feature of vim for me is the "dot" command. That doesn't seem to work with this plugin.

Steps to reproduce:
1. Insert 2 words (foo, bar)
2. Put your cursor over "foo" and type "ciw" to replace the word, and then type "CHANGED"
3. Now move your cursor to "bar" and hit the "." key. This SHOULD replace "bar" with "CHANGED" as well, but it doesn't. It seems to just delete the word.

**Comment by asvetliakov** [comment] 2020-01-31 17:27
Duplicate of #76

**Closed by asvetliakov** 2020-01-31 17:27 UTC
