### ISSUE TITLE
Remapping Escape to only jk without accepting jj?

### ISSUE THREAD

**Issue by DGalt** [asvetliakov/vscode-neovim#442] opened 2020-12-02 03:33 UTC
In other VIM emulators (which, understood, this is not) such as evil-mode in Emacs or VSCodeVim, it's been possible to remap escape to a combination such as jk or fd without jj or ff being accepted as escape keybindings as well. 

Looking at how `handleCompositeEscapeFirstKey` and `handleCompositeEscapeSecondKey` are implemented, it seems this is not possible for vscode-neovim. 

I.e. whatever key is specified for `compositeEscape1` will always act as escape when pressed twice (within the specified time window). 

Is this correct?

**Comment by asvetliakov** [comment] 2021-01-03 21:05
Duplicate of #166

**Closed by asvetliakov** 2021-01-03 21:05 UTC
