### ISSUE TITLE
digraphs in insert mode are not supported

### ISSUE THREAD

**Issue by FelipeLema** [asvetliakov/vscode-neovim#169] opened 2020-02-06 00:36 UTC
Hey, there

First: This is one of my favorite extensions. I really appreciate what y'all doing here.

ok, now the issue:

`CTRL-k` in insert mode doesn't work as with nvim. It's supposed to read two characters from the keyboard to insert an unicode char.

More info: `:help o_CTRL-k`

**Comment by asvetliakov** [comment] 2020-02-06 00:46
insert mode is controlled by vscode by design, so it won't be supported

**Closed by asvetliakov** 2020-02-06 00:46 UTC
Labels: wontfix

**Comment by mbway** [comment] 2024-06-09 12:56
If anyone else is looking for this functionality, I have a workaround that may be acceptable. The snippet below can be put in your neovim configuration and when `<leader>\` is pressed in normal mode (of course you can choose to trigger however you like) an input box opens. After typing two characters the box automatically closes and the digraph corresponding to your input gets inserted at the cursor.

```lua
vim.keymap.set('n', '<leader>\\', function()
    vscode.eval_async(
        [[
            return await new Promise((resolve) => {
                const box = vscode.window.createInputBox();
                box.title = "Digraph";
                box.onDidChangeValue((event) => {
                    if (box.value.length >= 2) { resolve(box.value); box.dispose(); }
                });
                box.onDidAccept((event) => { resolve(box.value); box.dispose(); });
                box.onDidHide((event) => { resolve(null); box.dispose(); });
                box.show();
            });
        ]],
        {
            callback = function(err, response)
                if response ~= vim.NIL and response:len() == 2 then
                    vim.fn.execute('normal i' .. vim.fn.digraph_get(response))
                end
            end
        }
    )
end)
```

**Comment by xiyaowong** [comment] 2024-06-09 13:12
No need to make it complicated.

```lua
vim.keymap.set('n', '<leader>\\', function()
  local msg = 'Get digraph of: '
  print(msg)
  local a = vim.fn.getcharstr()
  print(msg .. a)
  local b = vim.fn.getcharstr()
  print()
  local digraph = vim.fn.digraph_get(a .. b)
  vim.api.nvim_put({ digraph }, '', false, true)
end)
```
