### ISSUE TITLE
Word under cursor do not always highlighted properly

### ISSUE THREAD

**Issue by Shatur95** [asvetliakov/vscode-neovim#311] opened 2020-08-13 18:29 UTC
VSCode automatically highlights the usage of the word under the cursor. In insert mode everything works as expected, but in all other modes the word under the cursor is not always highlighted.

**Steps to reproduce**

1. Navigate to any word by mouse.
_The word is highlighted._
2. Navigate to one space after or before the word.
_The word is no longer highlighted, this is expected_
4. Navigate to word again with `b` or `w`.
_The wold still not highlighted_

**Expected behavior**

World is highlighted after step 4.

Same steps works as expected in insert mode.

**Comment by theol0403** [comment] 2020-08-14 03:14
Can confirm it does not work for me either. My solution is to use the [vim_current_word](https://github.com/dominikduda/vim_current_word) plugin, with this diff in vscode to make the underline and hl look nicer:

```
diff --git a/src/highlight_provider.ts b/src/highlight_provider.ts
index ee6fdb8..76a6875 100644
--- a/src/highlight_provider.ts
+++ b/src/highlight_provider.ts
@@ -46,7 +46,9 @@ function vimHighlightToVSCodeOptions(
     options.backgroundColor = uiAttrs.background
         ? "#" + uiAttrs.background.toString(16)
         : new ThemeColor("editor.background");
-    options.color = uiAttrs.foreground ? "#" + uiAttrs.foreground.toString(16) : new ThemeColor("editor.foreground");
+    if(uiAttrs.foreground) {    
+        options.color = "#" + uiAttrs.foreground.toString(16);
+    }
     const specialColor = uiAttrs.special ? "#" + uiAttrs.special.toString(16) : vimSpecialColor;
 
     if (uiAttrs.reverse) {
@@ -143,7 +145,7 @@ export class HighlightProvider {
 
     private configuration: HighlightConfiguration;
 
-    private specialColor = "orange";
+    private specialColor = "white";
     /**
      * Set of ignored HL group ids. They can still be used with force flag (mainly for statusbar color decorations)
      */
```


This is how it looks like for my theme:
![](https://cdn.discordapp.com/attachments/627866118249381888/735564478397284383/Peek_2020-07-22_11-29.gif)

However, solving the actual problem would be likely ideal.

**Comment by asvetliakov** [comment] 2020-08-17 01:57
The problem that manual vscode cursor assignment doesn't trigger editor highlight events, only commands do. That probably is not fixable on vscode side

**Comment by asvetliakov** [comment] 2020-09-04 11:49
Dupe of #159

**Closed by asvetliakov** 2020-09-04 11:49 UTC
Labels: vscode api required
