### ISSUE TITLE
Inaccurate visualization of line selection in visual mode

### ISSUE THREAD

**Issue by dschuessler** [asvetliakov/vscode-neovim#547] opened 2021-02-04 21:41 UTC
Steps to reproduce:

1. Type a line with more than 1000 characters.
2. Press Shift+V in normal mode to enter visual mode and select the entire line.

Expected behavior: The entire line looks selected.
Actual behavior: Only the first 1000 characters look selected.

https://user-images.githubusercontent.com/5774545/106958665-f66bf880-6739-11eb-9799-4ffdd69a4cdc.mov

Logically the entire line seems to be selected since pressing X deletes it entirely. So only the visual representation of the selection seems to be wrong.

**Comment by trkoch** [comment] 2021-02-06 13:09
I'm guessing this is related to the `neovimWidth` setting which is by default set to `1000`.

**Comment by theol0403** [comment] 2021-06-07 02:35
I'm going to mark this as a duplicate of #573 because it has more comments and a more concise title.

**Closed by theol0403** 2021-06-07 02:35 UTC
