### ISSUE TITLE
Programmatically detect running in vscode

### ISSUE THREAD

**Issue by docwhat** [asvetliakov/vscode-neovim#87] opened 2019-12-10 18:21 UTC
As an enhancement or alternative to #25 (custom init file):

It would be nice to be able detect if running under vscode.

I don't know if there would be a way to use `exists('vscode')` or something similar.

**Comment by asvetliakov** [comment] 2019-12-10 18:24
duplicate of #83

**Closed** 2019-12-10 18:24 UTC
Labels: duplicate
