### ISSUE TITLE
-- INSERT -- indicator on status bar remains in nomarl mode

### ISSUE THREAD

**Issue by tlannaax** [asvetliakov/vscode-neovim#422] opened 2020-10-30 19:51 UTC
Steps to reproduce: enter insert mode, type several characters and escape to normal mode. The "-- INSERT --" would remain on status bar.
Entering insert model and directly escape without typing gives the correct behavior: "-- INSERT --" disappears.

**Comment by myfoxit** [comment] 2020-11-24 10:57
I have the same issue on my vscode : 

nvim version : v0.5.0-812-gd17e50879
vscode : 1.50.0

**Comment by guyguy2001** [comment] 2020-11-27 21:01
I also have this issue, but only when using WSL.

NVIM v0.5.0-728-gf6ac37560
Build type: RelWithDebInfo
vscode; 1.51.1

**Comment by asvetliakov** [comment] 2021-01-03 20:29
Duplicate of #270

**Closed by asvetliakov** 2021-01-03 20:29 UTC
