### ISSUE TITLE
Feature request: <num><i><symbol>

### ISSUE THREAD

**Issue by poul1x** [asvetliakov/vscode-neovim#196] opened 2020-02-22 22:59 UTC
This command allows to create a sequence of the same chars. It's useful if you need to create strings like
1. \*************************** - 10i*
2. \================ - 10i=
3. e.t.c.

Futhermore, it allows to create N empty lines.

This feature is natively implemented in neovim:
- \<num\>\<i\>\<char\>
- \<num\>\<a\>\<char\>
- \<num\>\<I\>\<char\>
- \<num\>\<A\>\<char\>
- \<num\>\<o\>\<char\>
- \<num\>\<O\>\<char\>
- ...

**Comment by asvetliakov** [comment] 2020-02-22 23:06
Fixed by #173 
Duplicate of #190

**Closed by asvetliakov** 2020-02-22 23:06 UTC
