### ISSUE TITLE
alt- modifier not working (f.e. `nmap <a-j> exit` does not exit when I press `alt-j`)

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#463] opened 2020-12-29 02:50 UTC
I seem not to be able to do `alt-anything`.

I turned off the `Window: Custom Menu Bar Alt Focus` and `Window: Enable Menu Bar Mnemonics` options of VS Code, but no luck.

Any idea why no alt- combos work?

**Comment by trusktr** [comment] 2020-12-29 02:54
Oh, do we have to map every alt- key combo like was described for `alt-u` in https://github.com/asvetliakov/vscode-neovim/issues/189#issuecomment-587435080?

**Comment by asvetliakov** [comment] 2020-12-29 02:58
>Oh, do we have to map every alt- key combo like was described for alt-u in #189 (comment)?

Yes

**Comment by trusktr** [comment] 2020-12-29 03:01
Should it ship by default with the extension?

**Comment by asvetliakov** [comment] 2020-12-29 03:03
No. Otherwise we can block other extensions which are trying to use these keybinding, default vscode keybindings and custom user ones too.

**Comment by trusktr** [comment] 2020-12-29 03:10
The following makes all alt- letter combos work:

```json
[
    { "key": "alt+a", "command": "vscode-neovim.send", "args": "<a-a>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+b", "command": "vscode-neovim.send", "args": "<a-b>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+c", "command": "vscode-neovim.send", "args": "<a-c>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+d", "command": "vscode-neovim.send", "args": "<a-d>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+e", "command": "vscode-neovim.send", "args": "<a-e>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+f", "command": "vscode-neovim.send", "args": "<a-f>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+g", "command": "vscode-neovim.send", "args": "<a-g>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+h", "command": "vscode-neovim.send", "args": "<a-h>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+i", "command": "vscode-neovim.send", "args": "<a-i>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+j", "command": "vscode-neovim.send", "args": "<a-j>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+k", "command": "vscode-neovim.send", "args": "<a-k>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+l", "command": "vscode-neovim.send", "args": "<a-l>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+m", "command": "vscode-neovim.send", "args": "<a-m>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+n", "command": "vscode-neovim.send", "args": "<a-n>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+o", "command": "vscode-neovim.send", "args": "<a-o>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+p", "command": "vscode-neovim.send", "args": "<a-p>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+q", "command": "vscode-neovim.send", "args": "<a-q>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+r", "command": "vscode-neovim.send", "args": "<a-r>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+s", "command": "vscode-neovim.send", "args": "<a-s>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+t", "command": "vscode-neovim.send", "args": "<a-t>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+u", "command": "vscode-neovim.send", "args": "<a-u>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+v", "command": "vscode-neovim.send", "args": "<a-v>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+w", "command": "vscode-neovim.send", "args": "<a-w>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+x", "command": "vscode-neovim.send", "args": "<a-x>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+y", "command": "vscode-neovim.send", "args": "<a-y>", "when": "editorTextFocus && neovim.init" },
    { "key": "alt+z", "command": "vscode-neovim.send", "args": "<a-z>", "when": "editorTextFocus && neovim.init" },
]
```

Are there alt- bindings in VS Code, besides the file menu ones? I don't think I've ever used one.

I'm imagining that most Vim users will prefer their Vim alt- bindings over VS Code file menu bindings. Plus we have the command palette.

What if we add an option in the extension settings that we can toggle (prevents from having to paste the above in keybindings.json)?

**Comment by asvetliakov** [comment] 2020-12-29 03:16
it has some:
![image](https://user-images.githubusercontent.com/8881674/103256103-3ea23900-498c-11eb-84ea-e28b4c2a3ced.png)

vim doesn't have any meta keybindings by default as far as i know.

It's not possibly to dynamically register keybindings. So either we have something that breaks people for nothing by default, or we don't have it.

**Comment by trusktr** [comment] 2020-12-29 03:29
Ah, I see the options `Use Ctrl Keys For Normal Mode` and `Use Ctrl Keys For Insert Mode`, which are what allow my `<c- >` bindings to work instead of VS Code's ctrl- bindings.

What about similar `Use Alt Keys For Normal Mode` and `Use Alt Keys For Insert Mode` options, that are disabled by default?

**Comment by trusktr** [comment] 2020-12-29 03:31
I see that for some reason the `Use Ctrl Keys For Normal Mode` option is able to make `ctrl-k` bindings work (it successfully overrides the VS Code ctrl-k bindings), but it only isn't able to override the ctrl-j bindings? Why is this? Some sort of binding priority that extensions can not control?

**Comment by asvetliakov** [comment] 2020-12-29 03:32
Ah, yes, this one would work. Also there is #421 already. PRs welcome

**Comment by asvetliakov** [comment] 2020-12-29 03:34
>Why is this? Some sort of binding priority that extensions can not control?

Actually i'm not sure. I have default `<C-j>` not unbound , but it's being passed to neovim correctly

**Comment by trusktr** [comment] 2020-12-29 03:42
> > Why is this? Some sort of binding priority that extensions can not control?
> 
> Actually i'm not sure.

Yeah, the one I had to remove was a VS Code's mapping of `ctrl+j` to `editor.action.joinLines`. Doesn't seem like that comes from an extension. That mapping was higher up in the list than the neovim mappings (I'm guessing they appear in order, highest priority first).

**Comment by asvetliakov** [comment] 2020-12-29 03:46
>I'm guessing they appear in order, highest priority first)

Nope, alphabetically

>Also had to remove { "key": "ctrl+j", "command": "-workbench.action.togglePanel" },

That's culprit, because it doesn't have `when` and is being evaluated always

**Comment by trusktr** [comment] 2020-12-29 03:52
Oh, got it. So priority of whens. But in what order? What if two whens match?

**Comment by asvetliakov** [comment] 2020-12-29 03:57
i guess the extension one overrides default one. Not sure what will happen when two extensions are trying to bind same key with same/empty when. Probably the last loaded/alphabetically wins

**Comment by asvetliakov** [comment] 2021-01-03 20:34
Duplicate of #421

**Closed by asvetliakov** 2021-01-03 20:34 UTC
