### ISSUE TITLE
Typing "^" in normal mode to go to the binning of the line inserts "^"

### ISSUE THREAD

**Issue by dschuessler** [asvetliakov/vscode-neovim#231] opened 2020-03-24 22:24 UTC
If I am in normal mode and type a circumflex to go to the beginning of a line, a circumflex is inserted like it would in insert mode.

![Circumflex 2020-03-24 21_31_24](https://user-images.githubusercontent.com/5774545/77482559-7c36cc00-6e26-11ea-955e-954b78839cd3.gif)

Also happens with default settings and no other extensions enabled.

macOS 10.14.6
VSCode 1.43.1
vscode-neovim 0.0.50
Neovim 0.4.3
Keyboard layout: German

**Comment by dschuessler** [comment] 2020-06-01 09:23
I can now confirm that this only happens on keyboard layouts with dead keys.

**Comment by theol0403** [comment] 2021-06-15 07:16
Duplicate of #151

**Closed by theol0403** 2021-06-15 07:16 UTC
Labels: bug, help wanted
