### ISSUE TITLE
Append key (a) functions as Prepend key (i) in > 0.70 w/ NVIM 0.5.0

### ISSUE THREAD

**Issue by Syntaf** [asvetliakov/vscode-neovim#471] opened 2020-12-29 18:23 UTC
Ran into this issue when I upgraded from v0.0.63 to v0.0.70 (and onwards).

**Expected Behavior**: When I press `a` in visual mode, the cursor moves to the right and enters insert mode
**Actual Behavior**: When I press `a` in visual mode, the cursor functionals identical to `i` and moves left then enters insert mode

My NVIM version is `NVIM v0.5.0-828-g0a95549d6` - downgrading the extension to v0.0.63 solved this issue.

**Comment by Shatur95** [comment] 2020-12-29 18:24
Duplicate of #467.

**Closed by Shatur95** 2020-12-29 18:24 UTC

**Comment by Syntaf** [comment] 2020-12-30 16:25
Whoops, thought I had already searched for a duplicate issue, sorry and thanks!
